---
- name: Add apt-key
  apt_key: id=E56151BF keyserver=keyserver.ubuntu.com state=present

- name: Add Mesosphere repo
  apt_repository:
    repo: "{{ chronos_apt_repo }}"
    state: present

- name: Install Chronos package
  apt:
    pkg: chronos={{chronos_package_full_version}}
    state: present
    update_cache: yes
    cache_valid_time: 600
